### ISSUE TITLE
src error

### ISSUE THREAD

**Issue by eriDev1** [cosmicjs/unft-marketplace#15]
Hi, I just bumped into this error when cloned the repository: 

Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {"width":256,"height":120}

Thank you for your time and consideration !

**Comment by umr55766** [comment]
+1 
I'm also facing same issue
![image](https://github.com/cosmicjs/unft-marketplace/assets/16179313/338aa93c-6cdb-41e4-a717-b38b39cb4ea6)
![image](https://github.com/cosmicjs/unft-marketplace/assets/16179313/ff55e2e5-9f20-4452-b091-70651f5f3a2f)
Any suggestions/idea will be helpful.

**Comment by eriDev1** [comment]
Hi,

Thanks for reaching out!

If Im not mistaken I dumped this project because so many errors started
bumping out, but I believe to fix this one you should check the image size
and the size its being rended, because Next js doesn’t allow false
rendering hence its showing this error

Best of luck!

**Comment by tonyspiro** [comment]
This may have been an issue with the user added content missing data. This has been updated to connect to the new dashboard and API which should fix this issue.

**Comment by tonyspiro** [comment]
I recommend:
1. Log into the new Cosmic dashboard and create a new project. https://app.cosmicjs.com/login
2. Select start from template and choose the uNFT template.
3. Download the latest code from the repo which connects to the new dashboard since #17

I'm going to close this PR. Let me know if you run into any other issues! And thank you for the report 🙌🏻

**Comment by umr55766** [comment]
Thank you @tonyspiro. It worked!
