### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by umr55766** [cosmicjs/unft-marketplace#16]
When I am trying to install packages before running the app it is giving error while resolving dependencies.

![image](https://github.com/cosmicjs/unft-marketplace/assets/16179313/6e06f0fd-364d-4939-a8db-7f70225f9609)

Any thoughts ?

**Comment by umr55766** [comment]
I was able to make it work by downgrading few packages


```
"next": "10.2.0",
"next-connect": "^0.12.2",
"react": "^16.8.0",
"react-dom": "^16.8.0",

```

**Comment by tonyspiro** [comment]
Hi @umr55766 I've now updated this to connect to the new dashboard and API.

I recommend:
1. Log into the new Cosmic dashboard and create a new project. https://app.cosmicjs.com/login
2. Select start from template and choose the uNFT template.
3. Download the latest code from the repo which connects to the new dashboard since #17

I'm going to close this issue. Let me know if you run into any other issues! And thank you for the report 🙌🏻

**Comment by umr55766** [comment]
Thank you @tonyspiro. It worked!
